# -*- coding: utf-8 -*-
"""Project 103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Ahie010107/eed7dcd71f16c2a7575c7c89b4b48569/project-103.ipynb
"""

import pandas
import plotly.express as px

from google.colab import files
files.upload()

df = pandas.read_csv ("data0.csv")

df

mean = df.groupby(["student_id", "level"], as_index=False)["attempt"].mean()
fig = px.scatter(mean, x="student_id", y="level", size="attempt", color="attempt")
fig.show()